spring.application.name=heart_monitor


# Server
server.address=0.0.0.0
server.port=8080
server.servlet.context-path=

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/heart_monitor
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=10

# Logging
logging.level.root=INFO
logging.level.com.heartmonitor=DEBUG

# CORS
cors.allowed-origins=http://localhost:5173